site_name: BMEVIAUMB00 and BMEVIAUMB09 Business Intelligence Laboratory
site_author: Dudás Ákos
copyright: Copyright &copy; BME VIK AUT

repo_name: bi-labor/es-mssql
repo_url: https://github.com/bi-labor/es-mssql

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest
  logo: images/logo-bme-aut.png
  favicon: images/favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - "BI lab":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - GitHub-credentials.md
  - "Elasticsearch":
      - elasticsearch/index.md
      - elasticsearch/exercise1.md
      - elasticsearch/exercise2.md
      - elasticsearch/exercise3.md
      - elasticsearch/exercise4.md
      - elasticsearch/exercise5.md
      - elasticsearch/exercise6.md
      - elasticsearch/exercise7.md
      - elasticsearch/bme-cloud-vm-usage.md
  - "Pentaho":
      - pentaho/index.md
      - pentaho/exercise1.md
      - pentaho/exercise2.md
      - pentaho/exercise3.md
      - pentaho/exercise4.md
      - pentaho/exercise5.md
      - pentaho/exercise6.md
      - pentaho/exercise7.md
      - pentaho/exercise8.md
      - pentaho/bme-cloud-vm-usage.md
  - "MSSQL":
      - mssql/index.md
      - mssql/exercise1.md
      - mssql/exercise2.md
      - mssql/exercise3.md
      - mssql/exercise4.md
      - mssql/exercise5.md
      - mssql/exercise6.md
      - mssql/bi-software-intro.md
      - mssql/bme-cloud-vm-usage.md
