site_name: BMEVIAUMB00 Business Intelligence Laboratory
site_author: Dudás Ákos
copyright: Copyright &copy; BME AUT

repo_name: bi-labor/es-mssql
repo_url: https://github.com/bi-labor/es-mssql

theme:
  name: material
  custom_dir: theme-overrides
  language: en
  palette:
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
  logo: images/logo-bme-aut.png
  favicon: images/favicon.ico

extra_css:
  - extra-material-theme.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - "BI lab":
      - index.md
      - GitHub.md
      - GitHub-Actions.md
      - FAQ.md
      - GitHub-credentials.md
  - "Elasticsearch":
      - elasticsearch/index.md
      - elasticsearch/exercise1.md
      - elasticsearch/exercise2.md
      - elasticsearch/exercise3.md
      - elasticsearch/exercise4.md
      - elasticsearch/exercise5.md
      - elasticsearch/exercise6.md
      - elasticsearch/exercise7.md
  - "MSSQL":
      - mssql/index.md
      - mssql/exercise1.md
      - mssql/exercise2.md
      - mssql/exercise3.md
      - mssql/exercise4.md
      - mssql/exercise5.md
      - mssql/exercise6.md
      - mssql/bi-software-intro.md
      - mssql/bme-cloud-vm-usage.md
