name: Build Docker image for AHK

on:
  push:
    branches:
      - master
    paths:
      - "ahk/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub packages Docker registy
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push evaluator Docker image
        working-directory: ./ahk/evaluator
        env:
          DOCKER_REG_USERNAME: ${{ secrets.DOCKER_REG_USERNAME }}
          DOCKER_REG_TOKEN: ${{ secrets.DOCKER_REG_TOKEN }}
        run: |
          docker login -u $DOCKER_REG_USERNAME -p $DOCKER_REG_TOKEN
          docker-compose build
          docker-compose push
          docker logout

      - name: Logout from GitHub packages Docker registy
        if: ${{ always() }}
        run: docker logout docker.pkg.github.com
